// Generated by gencpp from file lab_2_3dPose/angles.msg
// DO NOT EDIT!


#ifndef LAB_2_3DPOSE_MESSAGE_ANGLES_H
#define LAB_2_3DPOSE_MESSAGE_ANGLES_H

#include <ros/service_traits.h>


#include <lab_2_3dPose/anglesRequest.h>
#include <lab_2_3dPose/anglesResponse.h>


namespace lab_2_3dPose
{

struct angles
{

typedef anglesRequest Request;
typedef anglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct angles
} // namespace lab_2_3dPose


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab_2_3dPose::angles > {
  static const char* value()
  {
    return "35dcb077bd4d3a7b8310b2de38d338fd";
  }

  static const char* value(const ::lab_2_3dPose::angles&) { return value(); }
};

template<>
struct DataType< ::lab_2_3dPose::angles > {
  static const char* value()
  {
    return "lab_2_3dPose/angles";
  }

  static const char* value(const ::lab_2_3dPose::angles&) { return value(); }
};


// service_traits::MD5Sum< ::lab_2_3dPose::anglesRequest> should match
// service_traits::MD5Sum< ::lab_2_3dPose::angles >
template<>
struct MD5Sum< ::lab_2_3dPose::anglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab_2_3dPose::angles >::value();
  }
  static const char* value(const ::lab_2_3dPose::anglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab_2_3dPose::anglesRequest> should match
// service_traits::DataType< ::lab_2_3dPose::angles >
template<>
struct DataType< ::lab_2_3dPose::anglesRequest>
{
  static const char* value()
  {
    return DataType< ::lab_2_3dPose::angles >::value();
  }
  static const char* value(const ::lab_2_3dPose::anglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab_2_3dPose::anglesResponse> should match
// service_traits::MD5Sum< ::lab_2_3dPose::angles >
template<>
struct MD5Sum< ::lab_2_3dPose::anglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab_2_3dPose::angles >::value();
  }
  static const char* value(const ::lab_2_3dPose::anglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab_2_3dPose::anglesResponse> should match
// service_traits::DataType< ::lab_2_3dPose::angles >
template<>
struct DataType< ::lab_2_3dPose::anglesResponse>
{
  static const char* value()
  {
    return DataType< ::lab_2_3dPose::angles >::value();
  }
  static const char* value(const ::lab_2_3dPose::anglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB_2_3DPOSE_MESSAGE_ANGLES_H
