// Generated by gencpp from file lab_2_3dPose/anglesResponse.msg
// DO NOT EDIT!


#ifndef LAB_2_3DPOSE_MESSAGE_ANGLESRESPONSE_H
#define LAB_2_3DPOSE_MESSAGE_ANGLESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab_2_3dPose
{
template <class ContainerAllocator>
struct anglesResponse_
{
  typedef anglesResponse_<ContainerAllocator> Type;

  anglesResponse_()
    : qx(0.0)
    , qy(0.0)
    , qz(0.0)
    , qw(0.0)  {
    }
  anglesResponse_(const ContainerAllocator& _alloc)
    : qx(0.0)
    , qy(0.0)
    , qz(0.0)
    , qw(0.0)  {
  (void)_alloc;
    }



   typedef double _qx_type;
  _qx_type qx;

   typedef double _qy_type;
  _qy_type qy;

   typedef double _qz_type;
  _qz_type qz;

   typedef double _qw_type;
  _qw_type qw;





  typedef boost::shared_ptr< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct anglesResponse_

typedef ::lab_2_3dPose::anglesResponse_<std::allocator<void> > anglesResponse;

typedef boost::shared_ptr< ::lab_2_3dPose::anglesResponse > anglesResponsePtr;
typedef boost::shared_ptr< ::lab_2_3dPose::anglesResponse const> anglesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab_2_3dPose::anglesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab_2_3dPose::anglesResponse_<ContainerAllocator1> & lhs, const ::lab_2_3dPose::anglesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.qx == rhs.qx &&
    lhs.qy == rhs.qy &&
    lhs.qz == rhs.qz &&
    lhs.qw == rhs.qw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab_2_3dPose::anglesResponse_<ContainerAllocator1> & lhs, const ::lab_2_3dPose::anglesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab_2_3dPose

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e41723dd8df2efa508384c23a439e4c";
  }

  static const char* value(const ::lab_2_3dPose::anglesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e41723dd8df2efaULL;
  static const uint64_t static_value2 = 0x508384c23a439e4cULL;
};

template<class ContainerAllocator>
struct DataType< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab_2_3dPose/anglesResponse";
  }

  static const char* value(const ::lab_2_3dPose::anglesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 qx\n"
"float64 qy\n"
"float64 qz\n"
"float64 qw\n"
;
  }

  static const char* value(const ::lab_2_3dPose::anglesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.qx);
      stream.next(m.qy);
      stream.next(m.qz);
      stream.next(m.qw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct anglesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab_2_3dPose::anglesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab_2_3dPose::anglesResponse_<ContainerAllocator>& v)
  {
    s << indent << "qx: ";
    Printer<double>::stream(s, indent + "  ", v.qx);
    s << indent << "qy: ";
    Printer<double>::stream(s, indent + "  ", v.qy);
    s << indent << "qz: ";
    Printer<double>::stream(s, indent + "  ", v.qz);
    s << indent << "qw: ";
    Printer<double>::stream(s, indent + "  ", v.qw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB_2_3DPOSE_MESSAGE_ANGLESRESPONSE_H
